# Generated by Django 3.1.5 on 2021-02-02 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='date_of_birth',
            new_name='date_of_exp',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='customer_id',
            new_name='prod_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='last_name',
        ),
    ]
